name: Run Pull Request Checks

on:
  pull_request: # Runs within the fork
    types:
      - opened
      - synchronize
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      conclusion: ${{steps.unit-tests.outputs.conclusion}}
      coverage: ${{steps.jacoco.outputs.coverage}}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt
      - name: Upload the PR number
        uses: actions/upload-artifact@v2
        with:
          name: pr_num
          path: ./pr_num.txt
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: mvn --batch-mode --update-snapshots verify