name: Run Pull Request Checks

on:
  pull_request: # Runs within the fork
    types:
      - opened
      - synchronize
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      conclusion: ${{steps.unit-tests.outputs.conclusion}}
      coverage: ${{steps.jacoco.outputs.coverage}}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: mvn --batch-mode --update-snapshots verify
      - name: Generate Test Reports
        continue-on-error: true
        id: unit-tests
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Reports
          path: target/test-results/*.xml
          reporter: java-junit
