name: Run Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      conclusion: ${{steps.unit-tests.outputs.conclusion}}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Test Report
        id: unit-tests
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test
          path: target/test-results/*.xml
          reporter: java-junit
  generate-badge:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    - uses: actions/checkout@v2
    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v1
      id: badge
      with:
        label: 'Test Result'
        status: ${{ needs.build.outputs.conclusion }}
        color: 'blue,555,daf'
        path: '.github/workflows/badge.svg'
    - name: Store badge
      uses: actions/upload-artifact@v2
      with:
        name: Test Results Badge
        path: '.github/workflows/badge.svg'
