name: Run Unit Tests

on:
  push:
    paths-ignore:
    - '**.md'
    - 'badges/**'
    

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      conclusion: ${{steps.unit-tests.outputs.conclusion}}
      coverage: ${{steps.jacoco.outputs.coverage}}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        continue-on-error: true
        run: mvn --batch-mode --update-snapshots verify
      - name: test
        continue-on-error: true
        id: unit-tests
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Reports
          path: target/test-results/*.xml
          reporter: java-junit
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: false
          jacoco-csv-file: target/site/jacoco/jacoco.csv

  generate-badge:
    runs-on: ubuntu-latest
    
    needs: build
    env:
      TEST_COLOUR: ${{ needs.build.outputs.conclusion == 'success' && 'success' || 'critical' }}
      COVER_COLOUR: ${{ needs.build.outputs.coverage >= 0.85 && 'success' || 'critical' }}
      RESULT: ${{ needs.build.outputs.conclusion == 'success' && 'PASS' || 'FAIL' }}
      COVERAGE_FLOAT: ${{ needs.build.outputs.coverage }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Configure environment
      run: echo "COVERAGE=$((${COVERAGE_FLOAT:0:4} * 100))" >> $GITHUB_ENV
    - name: Create directory for badges
      run: mkdir -p ".github/badges"
    - name: Create test badge
      run: curl https://img.shields.io/static/v1\?label\=Test%20Results\&message\=$RESULT\&color\=$TEST_COLOUR\&style\=for-the-badge\&link\=https://github.com/Matteas-Eden/yet-another-maven-repo/actions/workflows/run-test.yml > .github/badges/test-badge.svg
    - name: Create coverage badge
      run: curl https://img.shields.io/static/v1\?label\=coverage\&message\=$COVERAGE%25\&color\=$COVER_COLOUR\&style\=for-the-badge\&link\=https://github.com/Matteas-Eden/yet-another-maven-repo/actions/workflows/run-test.yml > .github/badges/cvrg-badge.svg
    - name: Commit badges
      run: |
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git add .github
        git commit -m "Update badges"
    - name: Push to master
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{github.token}}
        branch: master
